// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzqjdpncbxlujcjqrgvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56cWpkcG5jYnhsdWpjanFyZ3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDc0MTMsImV4cCI6MjA2NzgyMzQxM30.1IceaP7timZpbIQitG_Lf_WHEMkIjp6qz6bwKC0cY4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});